title:            Jahmel Harris
description:      Hacking is what I do
logo:             site-logo.png
disqus_shortname: sosimpletheme
search:           true
#Comment out url when working locally to resolve base urls correctly
url:              http://jahmelharris.github.io/blog

# Owner/author information
owner:
  name:           Jahmel Harris
  avatar:         jahmel-harris-photo.jpg
  email:          test@example.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        ""
  facebook:       ""
  github:         ""
  linkedin:       ""
  instagram:      ""
  tumblr:         ""
  stackexchange:  
  flickr:                 
  # For Google Authorship https://plus.google.com/authorship
  #google_plus:    "http://plus.google.com/118238196859537351707"

# Analytics and webmaster tools stuff goes here
#google_analytics:   UA-2011187-2
#google_verify:      UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:        D81F4C18A6CB3018F64D7C827D953DFD   

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Articles
    url: /articles/
  - title: Theme Setup
    url: /theme-setup/
  - title: Made Mistakes
    url: http://mademistakes.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
#pygments:    true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
